- tests/testthat/helper-gt_attr_expectations.R
- tests/testthat/test-gt_object.R
- vignettes/intro-creating-gt-tables.Rmd
> dplyr::data_frame deprecated

- R/format_data.R
- R/utils.R
- R/utils_formatters.R
- man/data_color.Rd
- man/fmt.Rd
- man/fmt_currency.Rd
- man/fmt_date.Rd
- man/fmt_datetime.Rd
- man/fmt_markdown.Rd
- man/fmt_missing.Rd
- man/fmt_number.Rd
- man/fmt_passthrough.Rd
- man/fmt_percent.Rd
- man/fmt_scientific.Rd
- man/fmt_time.Rd
- man/tab_footnote.Rd
- man/tab_header.Rd
- man/tab_options.Rd
- man/tab_row_group.Rd
- man/tab_source_note.Rd
- man/tab_spanner.Rd
- man/tab_stubhead_label.Rd
- man/tab_style.Rd
- tests/testthat/test-fmt_currency.R
- tests/testthat/test-fmt_number.R
- tests/testthat/test-fmt_percent.R
- tests/testthat/test-l_fmt_currency.R
- tests/testthat/test-l_fmt_number.R
- tests/testthat/test-l_fmt_percent.R
These changes provide a few more improvements to some `format_*()` functions and related utility functions.
> Make several refactoring improvements to some `format_*()` functions

- DESCRIPTION
- NEWS.md
This changes the version number to 0.2.0.9000 (an in-development version). Also, the NEWS.md file receives a new section.
> Change pkg version number to dev version

- DESCRIPTION
This PR updates the `Description` field inside of the package DESCRIPTION. 
Fixes: https://github.com/rstudio/gt/issues/519
> Update Description of package to be less confusing

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
This updates the R versions used in the GH workflow for R CMD check. Also, adds **covr** to Suggests in the DESCRIPTION file so that the `pkgdown` GH workflow can install **covr**.
Fixes: #567
> Update GH Actions workflow for R CMD check

- vignettes/case-study-gtcars.Rmd
- vignettes/creating-summary-lines.Rmd
- vignettes/gt-datasets.Rmd
- vignettes/intro-creating-gt-tables.Rmd
This makes changes to the vignettes/articles so that all code examples are compatible with the widespread API changes.
> Revise articles to use the enhanced tidyselect interface

- _pkgdown.yml
This adds missing topics to `_pkgdown.yml` so that the site builds.
> Add missing topics to _pkgdown.yml

- DESCRIPTION
- NEWS.md
This PR contains the changes required for the v0.3.0 CRAN release.
> v0.3.0 Release Candidate

- DESCRIPTION
- NEWS.md
This PR increases the version number to the corresponding dev version. This also adds a `NEWS.md` section for the upcoming release.
> Increment version number to 0.3.1.9000

- DESCRIPTION
- NEWS.md
This PR increases the version number to the corresponding dev version. This also adds a NEWS.md section for the upcoming release.
> Increment version number to 0.4.0.9000

- DESCRIPTION
- NEWS.md
This PR contains the changes required for the v0.5.0 CRAN release.
> v0.5.0 Release Candidate

- DESCRIPTION
- NEWS.md
This PR increases the version number to the corresponding dev version. This also adds a NEWS.md section for the upcoming release.
> Increment version number to 0.6.0.9000

- R/utils_render_html.R
This PR addresses #680.
This PR does not necessarily introduce any visual breaks.
> [Accessibility] Closing 680: Add scope = "col" for column headers

- R/zzz.R
> Document `gt.html_tag_check` opt

- DESCRIPTION
- NEWS.md
This PR increases the version number to the corresponding dev version. This also adds a NEWS.md section for the upcoming release.
> Increment version number to 0.7.0.9000

- DESCRIPTION
- NEWS.md
This bumps the version number to 0.8.0.9000, indicating a development version.
> Increment version number to 0.8.0.9000

- README.md
This corrects a small URL error for the R-CMD-check badge.
> Make correction to link to badge SVG

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- DESCRIPTION
- NEWS.md
- README.md
- man/gt-package.Rd
This PR updates email addresses, GHA workflow files, and copyright information.
> Perform various housekeeping updates

- R/utils_render_xml.R
- tests/testthat/test-as_word.R
Thank you for contributing to **gt**! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
Fix for the word implementation of the advanced footnote formatting
- Ref: #
> Word update for advanced footnote styling

- NEWS.md
- R/format_data.R
- R/modify_columns.R
- R/utils_render_common.R
- man/fmt_bins.Rd
- man/fmt_flag.Rd
- man/fmt_url.Rd
- vignettes/case-study-gtcars.Rmd
- vignettes/gt-datasets.Rmd
This PR has fixes for several types of documentation (help pages and vignettes mainly).
> Perform several documentation cleanups

- DESCRIPTION
- NEWS.md
- README.md
This bumps the version number to the dev version and revises the README.
> Use dev version past v0.9.0 release

- pkgdown/_pkgdown.yml
- pkgdown/extra.css
This PR updates the theme of the pkgdown site.
> Update theme of pkgdown site

- R/utils.R
- R/utils_examples.R
- tests/testthat/test-utils.R
This PR focuses on adding tests for utility functions that are currently not rigorously tested.
> Update and add tests for utility functions

- NEWS.md
This updates `NEWS.md` so that it's reasonably current.
> Update `NEWS.md` to include many changes for `v0.10.0`

- R/helpers.R
- R/utils_render_html.R
- man/system_fonts.Rd
This makes a few refinements to some of the system font stacks defined in `system_fonts()`.
> Update font stacks

- DESCRIPTION
- NEWS.md
- R/format_data.R
- R/helpers.R
- R/modify_columns.R
- R/tab_create_modify.R
- man/cols_label.Rd
- man/cols_units.Rd
- man/define_units.Rd
- man/fmt_units.Rd
- man/tab_spanner.Rd
This is the release candidate for gt v0.10.0.
> Release gt v0.10.0

- R/data_color.R
- R/dt_spanners.R
- R/modify_columns.R
- R/opts.R
- R/render_as_i_html.R
- R/utils.R
- R/utils_render_html.R
performance improvements for retrieving currency and for gt tbl checks.
> Performance improvement in options, currency and rendering

- R/resolver.R
- tests/testthat/test-cols_label_with.R
> fix namespaced call

- pkgdown/_pkgdown.yml
> add 0.11 blog post to pkgdown

- R/cols_add.R
- R/cols_align_decimal.R
- R/cols_label.R
- R/data_color.R
- R/format_data.R
- R/info_tables.R
- R/opts.R
- R/summary_rows.R
- R/utils_examples.R
- R/utils_plots.R
- R/utils_render_grid.R
- R/utils_render_latex.R
- R/utils_render_rtf.R
- R/utils_render_xml.R
- tests/testthat/test-fmt_number.R
Thank you for contributing to **gt**! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
- Ref: #
> Reduce pipe usage + code style

- DESCRIPTION
- R/data_color.R
- R/fmt_number.R
- R/format_data.R
- R/helpers.R
- data-raw/01-countrypops.R
- data-raw/05-pizzaplace.R
- man/cells_stub.Rd
- man/data_color.Rd
- man/fmt_auto.Rd
- man/fmt_integer.Rd
- man/fmt_number.Rd
- tests/testthat/test-as_raw_html.R
- tests/testthat/test-as_word.R
- tests/testthat/test-data_color.R
Tiny PR to use rlang for hashing and use `pivot_longer()` and `pivot_longer()` in examples
> Remove digest dep + update to tidyr 1.0 verbs in examples

- R/text_transform.R
- man/text_case_when.Rd
> fix example

- DESCRIPTION
- NEWS.md
This is the release candidate for gt v1.0.0.
> Release gt v1.0.0

- NEWS.md
Just spotted a typo while reading NEWS
> typo in NEWS.md
