R/format_data.R
tests/testthat/test-fmt_scientific.R

Previously, this code...
```r
dplyr::tibble(x = c(-15.0, -1.5, -0.001, NA, 0, 0.001, 1.5, 22.5, 333.5)) %>%
gt() %>%
fmt_scientific(columns = vars(x))
```
...would result in this error:
```
Error in FUN(X[[i]], ...) : subscript out of bounds 
```
The error occurred because there was no treatment of `NA`s as with the other `fmt*()` functions. With the changes here, we don't get an error and gt table output is correct:
A test was added to check the `fmt_scientific()` function for resilience to `NA` values.
This fixes #80.

Fix for using of `fmt_scientific()` on columns with NA values

---

R/utils_render_footnotes.R
tests/testthat/test-tab_footnote.R

Footnotes should always be put in the correct order (left-to-right then top-to-bottom). However, for footnote glyphs in the column labels, there was no strict ordering (i.e., left to chance by the API order). This example
```r
gtcars %>%
dplyr::filter(ctry_origin == "Germany") %>%
dplyr::group_by(mfr) %>%
dplyr::top_n(2, msrp) %>%
dplyr::ungroup() %>%
dplyr::select(mfr, model, drivetrain, msrp) %>%
gt() %>%
tab_footnote(
footnote = "Prices in USD.",
locations = cells_column_labels(columns = vars(msrp))
) %>%
tab_footnote(
footnote = "AWD = All Wheel Drive, RWD = Rear Wheel Drive.",
locations = cells_column_labels(columns = vars(drivetrain))
)
```
would produce the following HTML output table (which has an incorrect ordering of footnotes):
With the fixes in this PR, we now get the correct …

Fix for footnote ordering in column spanner labels and column labels

---

R/gt.R

Changes to grouped object attributes in dplyr mean that we need to update the way we extract grouping columns
See Issue #124

Changes to grouped object attributes in dplyr

---

R/format_data.R
R/utils.R
man/fmt_currency.Rd
man/fmt_number.Rd

This PR is meant for refactoring code relating to the scaling/suffixing of larger numbers. Two formatter functions (`fmt_number()` and `fmt_currency()`) have the `suffixing` argument that allows for this.

Refactor code related to the `suffixing` feature of `fmt_number()` and `fmt_currency()`

---

R/format_data.R
R/utils.R
tests/testthat/test-fmt_scientific.R

This fix modifies the `is_equal_to()` util function, which now uses an `identical()` comparison (instead of `all.equal()`) between two numbers. This has important implications for the `fmt_scientific()` formatter function because we compare whether a number is equal to zero and apply scientific notation when a number isn't zero (among other conditions not mentioned here).
Very small numbers would erroneously be deemed equal to zero before this change, resulting in incorrect formatting of such numbers in scientific notation.
Now, if we apply scientific notation to these numbers
`-1.5E200`, `-1.5E100`, `-2.5E0`, `-3.5E-100`, `-3.5E-200`, `1.5E-200`, `1.5E-100`, `2.5E0`, `3.5E100`, `3.5E200`
we get (in the default context)
`-1.50000 x 10(200)`, `-1.50000 x 10(100)`, `-2.50000`, `-3.50000 x …

Fix for `fmt_scientific()` when using very large or small numbers

---

R/format_data.R
man/fmt_number.Rd
man/fmt_percent.Rd

This addresses two spelling errors in the documentation. They were discovered variously by manual inspection and through use of `devtools::spell_check()`.

Fix spelling errors within the documentation

---

R/resolver.R
R/table_parts.R
man/tab_spanner.Rd
tests/testthat/test-l_table_parts.R
tests/testthat/test-table_parts.R

Currently, `tab_spanner()` will not move columns to create a contiguous block of columns under a spanner heading. While this is acceptable when you want a repeating spanner column label across the top of the column labels, it's likely not the most common use case. 
This change adds a `gather` argument that's set to `TRUE`. This makes it convenient for automatically gathering the columns that are part of a single spanner column label. Before the change, the user would have to carefully ensure the columns are contiguous before entry in `gt()`, or, would need to use some of the `cols_move*()` functions for manual movement of columns.
Here is an example where columns are automatically moved under the spanner column label
```r
gtcars %>%
dplyr::select(
-mfr, -trim, bdy_style, drivetrain, …
```

Add option to gather columns in `tab_spanner()`

---

R/utils_render_footnotes.R
R/utils_render_html.R
tests/testthat/test-table_parts.R

This PR addresses a bug where custom styles cannot be applied to stub row labels through `tab_style()` and `cells_group()`. For example, with
```r
exibble %>%
gt(rowname_col = "row", groupname_col = "group") %>%
tab_style(
locations = cells_group(groups = "grp_a"),
style = cells_styles(text_align = "center", bkgd_color = "lightblue")
)
```
we would get the error:
```
Error in arrange_impl(.data, dots) : 
Evaluation error: object 'colnum' not found. 
```
With the changes proposed here, we now get to style row group label cells.
```r
exibble %>%
gt(rowname_col = "row", groupname_col = "group") %>%
tab_style(
locations = cells_group(groups = "grp_a"),
style = cells_styles(text_align = "center", bkgd_color = "lightblue")
)
```
A testthat test was added to verify that custom styles could now …

Fix for `cells_group()` and it's use in `tab_style()`

---

.travis.yml

This updates the `travis.yml` file to deploy the **pkgdown** site to the `gh-pages` branch. A GitHub token (encrypted using the `travis` command line utility) has been added to automate the deploy. We now separate R CMD check, codecov, and pkgdown deploys into separate stages.
This will require some configuration in the repo as well. In the repository's **Settings**, the `Source` for `GitHub Pages` needs to be `gh-pages branch`

Travis Improvements, deployment of pkgdown site to gh-pages

---

.travis.yml

This simply removes the R check on Mac since it is currently not working. I will look at this periodically using another repo and reinstate this check when the Mac build system builds without error.

Remove Travis check on macOS

---

R/format_data.R
man/fmt_date.Rd
tests/testthat/test-fmt_date_time.R
tests/testthat/test-l_fmt_date_time.R

Currently, the `fmt_date()` function only works with character-based columns with an ISO formatted date or date-time. This PR makes it possible to also use values of type `Date` (as in the `sp500` dataset). The example in the `README` sidesteps the problem by mutating a date column (with `Date`s) to a `character` column:
```r
sp500 %>%
dplyr::filter(date >= start_date & date <= end_date) %>%
dplyr::select(-adj_close) %>%
dplyr::mutate(date = as.character(date)) %>%
gt() %>%
tab_header(
title = "S&P 500",
subtitle = glue::glue("{start_date} to {end_date}")
) %>%
fmt_date(
columns = vars(date),
date_style = 3
) %>%
fmt_currency(
columns = vars(open, high, low, close),
currency = "USD"
) %>%
fmt_number(
columns = vars(volume),
scale_by = 1 / 1E9,
pattern = "{x}B"
)
```
The PR makes this work …

Fix for `fmt_date()` that allows `Date` columns to work

---

README.Rmd
README.md

In these changes to the README, we:
- update the main example shown in the README (removes the `mutate()` line, uses the `suffixing` arg in `fmt_number()`)
- simplify the installation instructions
- remove the unneeded `library()` statements

Simple README updates

---

R/datasets.R
man/pizzaplace.Rd

This replaces a unicode character with its ascii equivalent. Solves a reported installation issue and is required by CRAN guidelines.
Fixes https://github.com/rstudio/gt/issues/216

Remove a unicode character from roxygen documentation

---

R/gt_options_default.R
R/render_as_html.R
R/tab_options.R
R/utils_render_html.R
man/tab_options.Rd
tests/testthat/test-cols_label.R

Sometimes it can be very useful not to have column labels at all. This PR makes that possible by providing the `column_labels.hide` argument in `tab_options()`. Here is a working example: 
```r
text_1a <- "
Markdown’s syntax is comprised entirely of
punctuation characters, which punctuation
characters have been carefully chosen so as
to look like what they mean... assuming
you’ve ever used email.
"
text_1b <- "
Info on Markdown syntax can be found
[here](https://daringfireball.net/projects/markdown/).
"
text_1c <- "<img src=\"https://i.imgur.com/3RqWtfL.gif\" width=\"200\">"
text_2a <- "
The **gt** package has these datasets:
- `countrypops`
- `sza`
- `gtcars`
- `sp500`
- `pizzaplace`
- `exibble`
"
text_2b <- "
There's a quick reference [here](https://commonmark.org/help/).
"
text_2c <- " …
```

Include option to hide all column labels

---

R/format_data.R
R/utils_formatters.R

This leaf branch makes a few additional changes to the PR of https://github.com/rstudio/gt/pull/244. Here we generate the textual marks right before usage using the supplied `context`.

Additional refactoring for `format_*()` functions

---

.travis.yml

This changes the travis YAML file to clean it up. This also uses functions from the remotes packages (instead of devtools).

Modify _travis.yml

---

R/modify_columns.R
tests/testthat/test-cols_merge.R

This is a small fix that inserts an empty string separator in the `sep` list component. This is important for the `cols_merge()` and `cols_merge_uncert()` functions as the `""` separator serves as a dummy value (whereas the `cols_merge_range()` function uses a non-empty separator).

Store empty-string value in `sep` vector

---

DESCRIPTION
R/gtsave.R
R/image.R
R/utils.R
man/local_image.Rd

This addresses https://github.com/rstudio/gt/issues/277, where file paths with `~`s aren't expanded. This also fixes other instances by normalizing file paths with `fs::path_expand()`.
Fixes: https://github.com/rstudio/gt/issues/277.

Path expand all file inputs

---

DESCRIPTION
R/shiny.R
man/gt_output.Rd
man/render_gt.Rd

This change enables to use of the `sass` package from CRAN and not from GitHub.
Fixes https://github.com/rstudio/gt/issues/83.
Fixes https://github.com/rstudio/gt/issues/254.

Use `sass` package from CRAN (not GitHub)

---

DESCRIPTION
R/format_data.R
R/helpers.R
R/utils.R
R/utils_render_common.R
man/cell_borders.Rd
man/cells_styles.Rd
man/fmt_number.Rd
man/location_cells.Rd

This is a fix `cell_borders()` being non-functional (https://github.com/rstudio/gt/issues/320).
Closes https://github.com/rstudio/gt/issues/320.
Closes https://github.com/rstudio/gt/issues/324.

Fix for `cell_borders()`

---

DESCRIPTION

This change is necessary while **sass** is being fixed for resubmission to CRAN.
Fixes https://github.com/rstudio/gt/issues/325.

Add `rstudio/sass` to Remotes list

---

.travis.yml
R/resolver.R
R/tab_footnote.R
R/tab_style.R
R/utils.R
R/utils_render_html.R
R/utils_render_latex.R
tests/testthat/test-location_cells.R

This PR addresses several deprecations warnings from **rlang**. The warnings were surfaced from running **testthat** tests. These warnings were:
- `prepend() is deprecated as of rlang 0.4.0.`
- `Subsetting quosures with [ is deprecated as of rlang 0.4.0 (Please use quo_get_expr() instead.)`
- `quo_expr() is deprecated as of rlang 0.2.0. (Please use quo_squash() instead.)`
- `Using as.character() on a quosure is deprecated as of rlang 0.3.0. (Please use as_label() or as_name() instead.)`
All problems fixed now and all tests pass without any warnings.
Fixes: https://github.com/rstudio/gt/issues/316.

Several `rlang`-based fixes

---

.travis.yml
R/tab_footnote.R
R/tab_style.R

This change uses the resolving function `resolve_data_vals_idx()` to correctly resolve the row group names from various types of inputs provided to `groups` in `cells_groups()`.
Fixes https://github.com/rstudio/gt/issues/308.

Fix for resolving row group cells

---

R/helpers.R

Both the `pct()` and `px()` don't allow `integer`-class values as input (only `numeric`). This PR allows the use of integers, so, this will now work:
```r
sp500 %>%
head() %>%
gt() %>%
tab_header(
title = "S&P 500",
subtitle = "5 rows"
) %>%
tab_spanner(
label = "prices",
columns = vars(open, high, low, close)
) %>%
fmt_date(
columns = vars(date),
date_style = 2
) %>%
fmt_currency(
columns = vars(open, high, low, close),
currency = "USD"
) %>%
fmt_number(
columns = vars(volume),
suffixing = TRUE
) %>%
tab_options(
table.font.size = px(10L)
)
```
Fixes: https://github.com/rstudio/gt/issues/307.

Allow use of integers in `pct()`/`px()`

---

R/utils_render_html.R

This is a simple fix to a `filter()` statement within `create_body_component_h()` that restores the ability to style stub cells. Here's a sample table after the fix is applied:
```r
sza %>%
dplyr::filter(
latitude == 20 & tst <= "1000") %>%
dplyr::select(-latitude) %>%
dplyr::filter(!is.na(sza)) %>%
tidyr::spread(key = "tst", value = sza) %>%
gt(rowname_col = "month") %>%
fmt_missing(
columns = TRUE,
missing_text = ""
) %>%
tab_style(
style = list(
cell_fill(color = "darkblue"),
cell_text(color = "white")
),
locations = cells_stub(rows = TRUE)
) %>%
tab_style(
style = list(
cell_fill(color = "lightblue"),
cell_text(color = "black")
),
locations = cells_data(rows = TRUE)
)
```
Fixes: https://github.com/rstudio/gt/issues/339.

Fix for `cells_stub()` stylizing helper function

---

R/gt_options_default.R
R/tab_options.R
inst/css/gt_styles_default.scss
man/tab_options.Rd

This PR allows us to use the `row_group.padding` option in `tab_options()` to specify a common padding value for row groups in a **gt** table (instead of the `8px` default). 
Here is an example:
```r
exibble %>%
gt(rowname_col = "row", groupname_col = "group") %>%
tab_options(row_group.padding = px(24))
```
Fixes: https://github.com/rstudio/gt/issues/327.

Enable option to set row group padding in `tab_options()`

---

inst/css/gt_styles_default.scss
tests/testthat/test-util_functions.R

This PR addresses the problem whereby gt tables, when rendered as HTML, have invisible top lines of cell borders (not visible unless `2px` or larger).
The problem is isolated to the CSS rules of the `gt_row` class:
```scss
.gt_row {
padding: $row_padding; /* row.padding */
margin: 10px;
border-bottom-style: solid;
border-bottom-width: thin;
border-bottom-color: #D3D3D3;
vertical-align: middle;
overflow-x: hidden;
}
```
Substituting all `border-bottom-*` rules for `border-top-*` avoids the line-drawing conflict between row lines and border lines. That is the only change in this PR and, through several visual tests, the changes made here fix the display issue.
Fixes: https://github.com/rstudio/gt/issues/358.

Fix for invisible top borders in rendered HTML tables

---

tests/testthat/test-gtsave.R

With an update in testthat, these tests worked fine locally but failed on Travis. I modified the approach to use `... %>% tidy_grepl() %>% expect_true()` instead of `expect_match()`. With this change, tests now pass on Travis (and locally, as before).

Fix testthat tests

---

R/helpers.R
man/cell_text.Rd

This allows for selected cells to have their contents vertically aligned (`top`, `center`, and `bottom`). Currently, the vertical alignment of all cell content is `center`; there's no easy way to change this.
This option is useful for tables with large chunks of text, where the less verbose columns end up way down the page. 
Here is an example where the option is used effectively:
```r
library(gt)
library(stringi)
long_text <- 
stri_rand_lipsum(3) %>%
str_c(., collapse = "\n")
data.frame(
index = c("I want this", "at the top", "of each cell"),
text = long_text
)  %>% 
gt() %>%
tab_style(
style = cell_text(v_align = "top"),
locations = cells_data()
)
```
All CI tests pass with this fairly minimal change.
Fixes https://github.com/rstudio/gt/issues/380

Add vertical align option in `cell_text()`

---

DESCRIPTION
R/format_data.R
R/utils_formatters.R
tests/testthat/test-fmt_number.R

Critical test is:
```r
library(gt)
tbl <- 
dplyr::tibble(
groups = c(rep("one", 5), rep("two", 5)),
rows = 1:10,
a = NA_real_
)
tbl %>%
gt() %>%
fmt_number(columns = vars(a))
```
Which shouldn't fail any more, but result in a column of unchanged NAs.
Fixes: https://github.com/rstudio/gt/issues/408

Fix error with `fmt_number()` on an NA-only column

---

DESCRIPTION
R/utils.R
R/utils_render_common.R
tests/testthat/test-gt_object.R

This change ensures that UTF-8 encoded characters don't get flattened to text during the building of table data. Change is focused on only the `migrate_unformatted_to_output()` internal function, where character values were passed through `format()` (now, only `numeric` vectors are).
Fixes: https://github.com/rstudio/gt/issues/419

Implement fix for UTF-8

---

R/helpers.R
man/cell_borders.Rd
man/cell_fill.Rd
man/cell_text.Rd
man/currency.Rd
man/escape_latex.Rd
man/figures/man_cell_borders_1.svg
man/figures/man_cell_borders_2.svg
man/figures/man_cell_fill_1.svg
man/figures/man_cell_text_1.svg
man/figures/man_currency_1.svg
man/figures/man_pct_1.svg
man/figures/man_px_1.svg
man/gt_latex_dependencies.Rd
man/html.Rd
man/md.Rd
man/pct.Rd
man/px.Rd
man/random_id.Rd

This expands on the documentation already available. Includes examples, SVGs, `@return` values, and more, for those functions previously missing those documentation features.
Fixes: https://github.com/rstudio/gt/issues/446
Fixes: https://github.com/rstudio/gt/issues/422

Expand documentation such that all functions get at least one self-contained example

---

R/data_color.R
R/export.R
R/format_data.R
R/modify_columns.R
R/modify_rows.R
R/summary_rows.R
R/tab_create_modify.R
R/text_transform.R
R/utils.R
man/fmt_number.Rd
tests/testthat/test-input_data_validation.R

This PR checks that the incoming data is a `gt_tbl` object (i.e., created by the `gt()` function). Column types are also checked in `fmt_*()` functions and `stop()`s are put into place for column types that won't be evaluated correctly.
Fixes: https://github.com/rstudio/gt/issues/444
Fixes: https://github.com/rstudio/gt/issues/449
Fixes: https://github.com/rstudio/gt/issues/385
Fixes: https://github.com/rstudio/gt/issues/205

Perform input validation and check for types when formatting

---

R/utils.R
tests/testthat/test-fmt_number.R

The `i` variable is used to index into the `suffixes`
vector, and previously, it could go negative because
log(n) is negative when 0 < n < 1.

Fix #397: error with suffixing=TRUE with abs(x) < 1

---

R/export.R
R/print.R

This change places the CSS styles inside of the `<head>`. This may be useful for ensuring that CSS styles are preserved in an email context.

Place style block in <head>

---

R/compile_scss.R
R/export.R
R/print.R
man/as_raw_html.Rd
tests/gt-examples/05-html-email/connect-example-main.Rmd

This adds an HTML dependency to the table when `as.tags()` is called (occurs during `knit_print()`ing an HTML document and during the print method. 
Fixes: https://github.com/rstudio/gt/issues/459

Add HTML dependency to the table

---

R/utils.R

This fix is isolated to the call of `as_raw_html(inline_css = TRUE)`, which is important for outputting HTML text of the table with inlined CSS styles for inclusion in HTML email message bodies.

Modify regex patterns to be less greedy during inline of CSS styles

---

R/dt_options.R
tests/testthat/test-tab_options.R

This change ensures that IE11 won't automatically bold the column labels. The `font-weight` property has been changed from `initial` to `normal`. Performed a manual test in my Windows 10 VM to make sure this change worked.
Fixes https://github.com/rstudio/gt/issues/430.

Modify default CSS option for column `font-weight`

---

tests/gt-examples/02-html-rmd/html-01-iris.Rmd
tests/gt-examples/05-html-email/emailing_table.R

This removes all use of the **emo** package from an example script that creates a table for a **blastula** email.

Remove use of emo package from example script

---

R/dt_stub_df.R
R/gt.R
tests/testthat/test-gt_object.R

This adds a `stop()` statement in the `gt()` function for the situation where any names supplied to `rowname_col` or `groupname_col` are shared amongst the two.
This will avoid any strange formatting of the table downstream. Furthermore, having columns specified in this way is probably not what the user wants anyhow (a clear error message provides the opportunity to correct the inputs for `gt()`).
Several **testthat** tests were added.
Fixes https://github.com/rstudio/gt/issues/474.

Error with any common name supplied to `rowname_col` or `groupname_col`

---

R/utils_render_html.R
inst/css/gt_styles_default.scss
tests/gt-examples/01-html-script/html-16-table_options_everywhere.R
tests/testthat/test-location_cells.R
tests/testthat/test-tab_spanner_delim.R
tests/testthat/test-table_parts.R
tests/testthat/test-util_functions.R

These changes improve the visual presentation of each spanner's bottom borders. It provides more separation between adjacent spanners and appears without defect in dark mode. 
The following code produces a gt table with two adjacent spanners:
```r
gtcars %>%
head(10) %>%
select(mfr, model, year, bdy_style, hp, hp_rpm, trq, trq_rpm, mpg_c, mpg_h) %>%
gt() %>%
tab_spanner(
label = "Car Model",
columns = vars(mfr,model,year)
) %>%
tab_spanner(
label = "Performance",
columns = vars(bdy_style,hp,hp_rpm,trq,trq_rpm,mpg_c,mpg_h)
) %>%
tab_header("gtcars dataset")
```
Fixes: #467 
Fixes: https://github.com/rstudio/gt/issues/74

Use alternate method to separate spanner lines

---

tests/testthat/test-gt_object.R

This PR ensures that system locales are available on the test system and also it constrains them to an already specified set.

Update testthat tests for UTF-8 characters across system locales

---

README.Rmd
README.md

This PR updates the README with a new section called `Other Packages that Generate Display Tables`. It points out that there are several other R packages for generating display tables and provides a list of names and links to relevant pages.

Update README with information on other table-making packages

---

R/utils_render_html.R
tests/testthat/test-table_parts.R

This PR fixes the method in which `colspan` values for spanners are calculated, using `rle()` instead of `duplicated()` in complicated `for` loop. 
Fixes #506

Use `rle()` to determine colspan values for spanners

---

R/gt_preview.R
tests/testthat/test-gt_preview.R

When using `gt_preview()` on a table with a `Date` column, we get an error because an empty string (which we use as a dividing row in an `rbind()` operation) cannot be coerced to a `Date`.
With:
```r
gt_preview(sp500)
```
We get the error:
```
Error in charToDate(x) : 
character string is not in a standard unambiguous format
```
The first column `date` is of the `Date` class. We get the same error with `as.Date("")`.
Any columns that are date-times (`POSIXct`) don't fare any better. That associated error is:
```
Error in as.POSIXlt.character(x, tz, ...) : 
character string is not in a standard unambiguous format
```
The solution is to use `NA`s for the dividing row in the `rbind()` call of `gt_preview()`. To ensure that this works across a wide variety of input tables, I've added numerous …

Fix to avoid error in `gt_preview()` with columns that contain dates

---

R/export.R
man/gtsave.Rd

This PR wraps `\dontrun{}` around the examples in the `gtsave()` doc to avoid a R CMD check issue on Travis.

Add \dontrun{} around `gtsave()` examples

---

R/export.R

This removes `wait = TRUE` from an internal `webshot()` call.
Fixes: #542

Remove `wait = TRUE` from `webshot()` call

---

.github/workflows/pkgdown.yaml

This attempts to resolve the issue where the package cache needs to be cleared because of an install issue. (Hoping that GitHub will make this easier in the future.)

Bump cache on pkgdown.yaml for GH workflow

---

DESCRIPTION
NEWS.md
R/dt_styles.R
R/export.R
man/gtsave.Rd

The change made removes an unnecessary subsetting operation on a tibble. With the subsetting in place, although it gives an identical result, we get a warning in tibble 3.0.0/3.0.1. See https://cran.r-project.org/web/packages/tibble/vignettes/invariants.html for details (example is `df[10, ]`).
This PR also addresses a remaining issue with the roxygen `dontrun / donttest` directive in the `gtsave()` docs (removes it)

Squelch warnings from tibble 3.0.0/3.0.1

---

tests/testthat/test-data_color.R

You accidentally depended on a scales 1.1.0 bug (and in general,  it's a bad idea to test errors generated by other packages).
Is there any chance you could do a quick gt release with this fix so I can submit scales to CRAN in the near future?

Remove test of scales behaviour

---

R/format_data.R
man/fmt_percent.Rd
man/gt-package.Rd

This updates an example where dplyr's `n()` function wasn't found because it wasn't in the form `dplyr::n()`. This also roxygenizes the package article (`gt-package`), which was missed in an earlier PR where the package `Description` was modified.

Update failing example

---

R/data_color.R
man/data_color.Rd
man/gt-package.Rd

The `data_color()` function was seen to be extremely slow. Reason for this was a combination of missed opportunities for vectorization, overuse of loops, and longer than necessary routes to an otherwise simple addition of `_styles` rows.
Below is reproducible code that would otherwise take 5-8 s before the changes in this PR (it now takes about 0.15 seconds):
```r
library(gt)
library(scales)
library(paletteer)
sza %>%
dplyr::filter(latitude == 20) %>%
dplyr::select(-latitude) %>%
dplyr::filter(!is.na(sza)) %>%
tidyr::spread(key = "tst", value = sza) %>%
gt(rowname_col = "month") %>%
fmt_missing(
columns = TRUE,
missing_text = ""
) %>%
data_color(
columns = TRUE,
colors = scales::col_numeric(
palette = paletteer::paletteer_d(
palette = "ggsci::orange_material"
) %>% …
```

Refactor `data_color()` so that it executes faster

---

DESCRIPTION
NEWS.md
inst/css/gt_styles_default.scss
man/data_color.Rd
man/gt-package.Rd
man/gtsave.Rd
man/reexports.Rd

This simply moves the `.gt_striped` rule below others to increase precedence.
Thanks @gergness for creating the PR that prompted this one (https://github.com/rstudio/gt/pull/537). We ultimately decided to go with this change (which restores the earlier behavior) since it work better with HTML style inlining (using `as_raw_html()`).
Testable code from @gergness, where the yellow row stripes are also present in the stub cells (leftmost column).
```r
library(gt)
exibble %>% 
gt(rowname_col = "row") %>% 
opt_row_striping() %>% 
tab_options(
row.striping.include_stub = TRUE,
row.striping.background_color = "yellow"
)
```
Fixes: https://github.com/rstudio/gt/issues/536

Restore row striping option in stub cells (`row.striping.include_stub = TRUE`)

---

DESCRIPTION

from `DESCRIPTION`. This ensures that the site is found from the CRAN package page and that pkgdown autolinking forwards to that documentation.

Link to documentation site

---

R/gt-package.R
R/helpers.R
R/zzz.R
_pkgdown.yml
man/cells_data.Rd
man/cells_group.Rd
man/gt-options.Rd
man/gt-package.Rd

This PR adds some help topics to the `reference` section of the `_pkgdown.yml` file. Some topics are excluded (deprecated functions, etc.) and so the `@keywords internal` roxygen tag was added to those and the help files were roxygenized. This is all to avoid the error by dev pkgdown in the GHA build that generates the pkgdown site for gt.

pkgdown updates

---

DESCRIPTION
R/dt_options.R
R/gt.R
R/knitr-utils.R
R/render_as_html.R
R/utils.R
R/utils_render_html.R
man/gt.Rd
tests/testthat/helper-gt_attr_expectations.R
tests/testthat/test-utils_render_html.R

This PR adds caption support for gt tables, making captions work in R Markdown and in bookdown.
Fixes: #115

Add the `caption` arg to `gt()`; support bookdown crossrefs

---

R/utils_render_footnotes.R

This changes replaces `group_by()` with `group_by_at()` to avoid using the deprecated `.dots` argument. No functionality has changed, this serves to remove the deprecation warning whenever the user calls `tab_style()` or `tab_footnote()` on a gt table.
Fixes: #709

Avoid use of `group_by()` `.dots` deprecation by using `group_by_at()`

---

R/modify_columns.R
man/cols_align.Rd

Hey all, I noticed a small typo in the documentation for the cols_align() function, so I updated it in modify_columns.R and regenerated the docs with devtools::document().

fixed typo in modify_columns.R documentation

---

R/knitr-utils.R
tests/testthat/test-utils_render_html.R

This will fix #719 
The escaping of # in `(\\# ... )` is not needed because the syntax won't be processed by Pandoc. This does not need to be escape. 
**bookdown** reference mechanism works by matching `(#tab:label)` 
This will fix the auto numbering of the reference.
But there is also an issue because `(#tab:label)` is not removed from the caption. I think this needs to be patched in **bookdown**.
Just sharing this to easily show the fix and test. I let you decide if you want to fix differently.

Fix for bookdown table reference support

---

tests/gt-examples/01-html-script/html-06-mtcars.R
tests/gt-examples/01-html-script/html-15-styles_everywhere.R
tests/gt-examples/02-html-rmd/html-06-mtcars.Rmd
tests/gt-examples/02-html-rmd/html-15-styles_everywhere.Rmd
tests/gt-examples/03-latex/latex-06-mtcars.Rmd

Some examples in `tests/gt-examples` failed because the call to `tab_row_group()` wasn't updated to the new API. This PR corrects those examples.
Fixes: #740

Make corrections to some examples

---

R/tab_create_modify.R
man/tab_row_group.Rd
tests/testthat/test-table_parts.R

This reinstates the `group` argument in `tab_row_group()` and uses any value present for `group` (while issuing a warning). New unit tests check that the added logic is correct.

Add `group` arg to `tab_row_group` for deprecation

---

R/utils_render_common.R
R/utils_render_latex.R
tests/testthat/test-gt_object.R

This PR is a bugfix for rendering LaTeX tables that have a stub. The issue in the rendering was that row splits were incorrectly made because there was no consideration of the stub var in the vector of visible vars.

Rendering fix for LaTeX tables that have a stub column

---

R/format_data.R
man/fmt_bytes.Rd
man/fmt_currency.Rd
man/fmt_engineering.Rd
man/fmt_integer.Rd
man/fmt_number.Rd
man/fmt_percent.Rd
man/fmt_scientific.Rd
tests/testthat/test-fmt_bytes.R
tests/testthat/test-fmt_engineering.R
tests/testthat/test-fmt_integer.R
tests/testthat/test-fmt_number.R
tests/testthat/test-fmt_percent.R
tests/testthat/test-fmt_scientific.R
tests/testthat/test-l_fmt_engineering.R
tests/testthat/test-l_fmt_integer.R
tests/testthat/test-l_fmt_number.R
tests/testthat/test-l_fmt_percent.R
tests/testthat/test-l_fmt_scientific.R

This PR adds the option to always show either a positive or negative sign. This is especially important when reporting change values. Exceptions to this rule occur with exact zero values and when using the accounting format.
Fixes: https://github.com/rstudio/gt/issues/773

Add the `force_sign` arg to several numeric formatters

---

man/figures/gt_workflow_diagram.svg

This corrects the `gt_workflow_diagram.svg` file, which is used in `README.md`. Previously, there wasn't a background set, making the image difficult to read when in Dark Mode. This change adds a white background to the aforementioned SVG file (as with the other SVGs in the README).

Ensure that `gt_workflow_diagram.svg` has a white background set for Dark Mode GH users

---

R/dt_summary.R
tests/testthat/test-gt_object.R

Previously, summary rows were not honoring the `locale` that may have been set in the initial `gt()` call. This was an oversight that is now fixed in this PR.
Now, the following code should produce correctly rendered summary cells:
```r
exibble %>%
dplyr::select(num, row, group) %>%
gt(rowname_col = "row", groupname_col = "group", locale = "de") %>%
fmt_number(columns = num, decimals = 2) %>%
summary_rows(
groups = c("grp_a", "grp_b"),
columns = num,
fns = list(mean = ~ mean(., na.rm = TRUE))
)
```
Fixes: https://github.com/rstudio/gt/issues/906

Honor default `locale` setting when rendering summary rows

---

R/helpers.R
man/escape_latex.Rd
tests/testthat/test-escaping.R

Certain replacements for LaTeX escapes that supply a command will render better (i.e., not include unwanted space characters) if they use `{}` (e.g., `\textasciitilde{}` instead of `\textasciitilde `). To that end, this PR enhances the `escape_latex()` function to make the replacements render LaTeX text more accurately.

Update `escape_latex()` for better rendering

---

R/utils_render_html.R

This PR addresses #679: now screen readers don't get confused when using title and subtitle element.
``` r
library(gt)
airquality[1:10, ] %>%
gt::gt() %>%
gt::tab_header(
title = "Title",
subtitle = "Subtitle"
)
```
`title` and `subtitle` now get treated as `<td>`. This is good for screen reader a11y.
@rich-iannone, I still need your help to verify whether there are any CSS tweaks that we need to consider. I don't want to introduce any visual breaks.

[Accessibility] Closing #679: Use <td> instead of <th> for title and subtitle

---

R/tab_create_modify.R
R/utils.R
tests/testthat/test-util_functions.R

Currently, we use `check_spanner_id_unique()` to validate whether an ID value for a new column spanner is unique. The uniqueness check only considers the closed set of existing column spanner ID values. The changes here ensure that the column spanner IDs are unique across all cells that use the `<th>` tag (this includes column names and spanner column names).
Fixes: #991

Ensure that unique IDs are maintained across columns spanners and column headers

---

DESCRIPTION
R/build_data.R
R/tab_create_modify.R
R/utils_formatters.R

The `checkmate` package's assertion functions were not really used comprehensively in gt and we have robust checking throughout anyway. So, it seemed prudent to remove the dependency on that package and provide suitable assertion replacements where needed, and that's what this PR delivers.

Remove dependency on checkmate

---

R/export.R
man/gtsave.Rd

This adds a return value (`invisible(TRUE)`) to the bottom of the `gtsave()` function body. This clears up the issue of unwanted printing in R Markdown / Quarto documents and usefully returns `TRUE` in case the user needs to log the outcome of a `gtsave()` call. This also adds to and cleans up documentation in `gtsave()`.
Fixes https://github.com/rstudio/gt/issues/974

Add return value for `gtsave()`

---

R/utils.R

This PR fixes an error in a `filter()` statement. The `&&`s should rightly be `&`s. This clears a warning with newer versions of R and correctly filters the table that this statement operates on.
Fixes: https://github.com/rstudio/gt/issues/1004

Use `&` instead of `&&` in `filter()` stmt

---

R/z_utils_render_footnotes.R
tests/testthat/_snaps/tab_footnote.md
tests/testthat/test-tab_footnote.R

This PR ensures that table body cell text generated from `fmt_markdown()` can have footnote marks inline with the produced text. This fix works both for right and left placement of the footnote marks. New testthat tests were added to address these changes.
Fixes: https://github.com/rstudio/gt/issues/993
Fixes: https://github.com/rstudio/gt/issues/893

Better integrate footnote marks with table cell text rendered with `fmt_markdown()`

---

R/utils_render_html.R
R/utils_render_latex.R
R/utils_render_rtf.R
R/z_utils_render_footnotes.R
tests/testthat/_snaps/tab_footnote.md
tests/testthat/test-tab_footnote.R
text.rtf

When formatting a table with a two-column stub arrangement, the group label wasn't being used to generate the cell matrix (the left-most cell corresponding to a group label was taken from the table body). This is wrong as the group labels are placed in the `groups_rows_df` table, where they undergo rendering and that's where footnote marks are affixed to them.
This PR modifies the body row rendering in the separate HTML, LaTeX, and RTF implementations. Several snapshot tests have been added to capture the fix. Here is the code that illustrates the problem, with a screenshot showing that the change was successful.
```r
pizzaplace %>%
dplyr::filter(name %in% c("soppressata", "peppr_salami")) %>%
dplyr::group_by(name, size) %>%
dplyr::summarize(`Pizzas Sold` = dplyr::n(), .groups = "drop") …
```

Ensure that the row group labels in a two-column stub can render footnote marks

---

R/tab_create_modify.R
tests/testthat/test-tab_spanner_delim.R

In more complex situations, `tab_spanner_delim()` would fail to generate unique ID values. This is now fixed by adding an index to the first-duplicated ID value and incrementing by 1 for subsequent duplications. Now this works:
```r
library(gt)
dplyr::tibble(
a.i.x = "",
b.i.x = "",
a.j.x = "",
b.j.x = "",
a.i.y = "",
b.i.y = "",
a.j.y = "",
b.j.y = "",
a.i.z = "",
b.i.z = "",
a.j.z = "",
b.j.z = ""
) %>%
gt() %>%
tab_spanner_delim(
delim = ".",
split = "first"
)
```
Also, using `split = "last"` also works. Added several testthat tests for this.
Fixes: https://github.com/rstudio/gt/issues/1000

Fix spanner ID generation in `tab_spanner_delim()`

---

R/export.R
man/as_latex.Rd

When I was working with a custom beamer template, the `as_latex()` function didn't add the appropriate package dependencies to the header. I've added a bit of documentation to emphasize the requirements and steps to take to ensure smooth sailing.
Resubmission of #615 
Close #615

Update as_latex() documentation to include steps to take to ensure dependencies are present when rendering the document. 

---

R/format_data.R
R/format_vec.R
R/utils.R
man/fmt_date.Rd
man/fmt_datetime.Rd
man/fmt_time.Rd
man/vec_fmt_date.Rd
man/vec_fmt_datetime.Rd
man/vec_fmt_time.Rd
tests/testthat/test-fmt_date_time.R
tests/testthat/test-l_fmt_date_time.R
tests/testthat/test-util_functions.R
tests/testthat/test-vec_fmt.R

This includes the `"day_m"` option for formatting dates with `fmt_date()` and `vec_fmt_date()`. This makes it possible to have a very short date (w/ implied year) in the table stub.
Now we can something like this:
```r
exibble %>%
dplyr::select(date, time) %>%
gt(rowname_col = "date") %>%
fmt_date(
columns = date,
date_style = "day_m"
) %>%
cols_align(
align = "left",
columns = stub()
) %>%
sub_missing(
columns= stub(),
missing_text = ""
)
```
Fixes: https://github.com/rstudio/gt/issues/1028

Include `"day_m"` option in `fmt_date()` and `vec_fmt_date()`

---

DESCRIPTION
R/format_data.R
R/info_tables.R
R/utils.R
R/utils_general_str_formatting.R
R/utils_render_rtf.R

This PR removes the few stringr functions that remained in the package. A handful of simple replacement functions are used instead.

Replace stringr functions with base R equivalents

---

.Rbuildignore
R/export.R
man/extract_cells.Rd
tests/testthat/test-extract_cells.R

This PR refines the new `extract_cells()` function by changing the internal build process (using a partial build that avoids the attachment of footnote marks to text), revising the documentation, and adding tests.

Revisions to the `extract_cells()` function

---

tests/testthat/test-data_color.R

While working on another issue, I had a test that failed because paletteer was not installed.  Skip those tests when it is not installed.

Skip if paletteer is not installed

---

DESCRIPTION
R/data_color.R
R/utils_color_contrast.R
man/data_color.Rd
tests/testthat/test-color_handling.R
tests/testthat/test-data_color.R

This updates the `ideal_fgnd_color()` util function add the APCA contrast also. This determines Lc contrast between overlaid text on a background color. The background is fixed and the text color is swapped to the alternative (`light` or `dark`) that maximizes contrast. The code here is adapted from the SAPC APCA (Accessible Perceptual Contrast Algorithm). The WCAG algo has been added here as a (non-default) alternative in `data_color()`. Here is a comparison table demonstrating the differences between the WCAG and APCA contrast schemes.

Use the APCA contrast algorithm to better select light or dark text in `ideal_fgnd_color()`

---

R/utils_render_html.R

The `tab_style()` function allows for raw styles to be added as in the `style` list. This PR removes the string manipulation of inserting a space character after any colon. This is unnecessary and also disrupts any rules that contain a colon within the value portion (e.g., URLs enclosed in `url()`.
Fixes: https://github.com/rstudio/gt/issues/1083

Don't manipulate raw style rules (i.e., strings) as input to `tab_style()`

---

.Rbuildignore
R/dt_boxhead.R
R/modify_columns.R
tests/testthat/_snaps/cols_merge.md
tests/testthat/test-cols_merge.R

This PR allows the stub contents to freely merge with other columns (using the `cols_merge*()` functions). With this, the stub won't be accidentally hidden since the logic behind that was altered to exclude the hiding of columns designated as the stub.

Allow the table stub to participate in column merging operations

---

.Rbuildignore
DESCRIPTION
R/utils_render_rtf.R
tests/testthat/_snaps/group_column_label.md
tests/testthat/_snaps/rtf_page_options.md

This fix ensures that spanner column labels are rendered correctly in a wider variety of RTF applications (OpenOffice, Apple TextEdit, MS Word, etc.). Previously, Word could work around the non-ideal RTF generated but the fix ensures that more renderers display spanner column labels properly.
Fixes: https://github.com/rstudio/gt/issues/1054

Fix display of spanner column labels in different applications that render RTF

---

R/render_as_html.R
tests/testthat/test-as_raw_html.R
tests/testthat/test-r_table_parts.R

This PR fixes an issue where font names containing spaces (i.e., require single quotes as CSS values) are transformed to HTML entity values by htmltools (unavoidable) and cannot be parsed by the CSS inliner when using `as_raw_html(inline_css = TRUE)`. This change unescapes single quotes and adds several testthat tests.
Fixes: https://github.com/rstudio/gt/issues/1123

Fix for multiword font-family values and `as_raw_html(inline_css = TRUE)`

---

R/helpers.R
man/cell_borders.Rd

This adds the 'double' option as a border option in `cell_borders`.
Fixes: https://github.com/rstudio/gt/issues/1132

Add 'double' as border style option

---

R/dt_summary.R
R/format_data.R
R/format_vec.R
R/summary_rows.R
R/utils.R
R/utils_formatters.R
R/utils_general_str_formatting.R
man/fmt_engineering.Rd
man/fmt_scientific.Rd
man/vec_fmt_engineering.Rd
man/vec_fmt_scientific.Rd
tests/testthat/test-fmt_engineering.R
tests/testthat/test-fmt_scientific.R
tests/testthat/test-l_fmt_engineering.R
tests/testthat/test-l_fmt_scientific.R
tests/testthat/test-vec_fmt.R

This adds new features to `fmt_scientific()` and `fmt_engineering()`. One is an `exp_style` option to both functions, allowing for some choice for type of exponent used. Forcing a positive sign can now be done to the `m` *and* `n` parts of the notation. The PR also updates the documentation for these functions.

Enhancements to `fmt_scientific()` and `fmt_engineering()`

---

inst/css/gt_styles_default.scss

This adds a single rule to the SCSS class `.gt_footnote_marks` to ensure that the footnote mark is at a consistent height from the baseline in different CSS environments.

Add `position: initial;` CSS rule for footnotes

---

R/format_data.R

This fixes an error where color normalization in `fmt_url()` should only occur if the value of the color is not `"auto"`.

Only normalize `color` in `fmt_url()` if not 'auto'

---

R/dt_options.R
R/render_as_html.R
R/tab_create_modify.R
man/tab_options.Rd
tests/testthat/helper-gt_attr_expectations.R

This adds an option in `tab_options()` (`quarto.disable_processing`) that disallows Quarto from modifying a gt table. This is useful in cases where you'd like the table to appear close to what you'd see in the Viewer (render of table in an otherwise empty HTML page).

Add option to disable table processing by Quarto

---

DESCRIPTION
R/export.R

This PR puts `juicyjuice` as an optional install, since it is only used in one function (`as_raw_html()`) and some people had trouble installing the package because it uses V8.
Fixes: #1179

Use `juicyjuice` as a soft dependency

---

R/dt_boxhead.R
R/utils.R

This allows for column labels to be obtained from any columns that have a `label` attribute. For those columns not having an attribute (in a mixed case), the fallback will be the column name. In cases where there are no such attrs for any columns, we use the original codepath (in `dt_boxhead_init()`).
Fixes: https://github.com/rstudio/gt/issues/656

Recognize and utilize column labels inside column data attires

---

inst/css/gt_styles_default.scss

This provides a simple yet important correction to the rules within the `.gt_footnote` class.

Make correction to SCSS for `.gt_footnote`

---

R/modify_columns.R

This small fix ensures that any input provided to `cols_label()` as a list (for the `.list` arg) does not fail.

Add fix for `cols_label()` that supports input from `.list` arg

---

R/render_as_i_html.R

This small fix ensures that column sorting works properly. Previously the formatted cells were given as input to the interactive table. Now, the underlying data (with their original types) is given and formatted cells are provided in column definitions.

Fix issue with column sorting in interactive tables

---

R/substitution.R
man/sub_small_vals.Rd

Improve the documentation for the `sub_small_vals()` function so that it is clear that the interval does not include zero or the threshold value.
Fixes: https://github.com/rstudio/gt/issues/1228

Improve documentation for the `sub_small_vals()` function

---

R/export.R
R/utils_render_xml.R

Add iconv to gtsave output to ensure utf-8 output and handle multiple length values in parse_to_xml
Thank you for contributing to **gt**! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
Review of open PRs,  closes #1204, #1057
- Ref: #

wrapping up word updates for V0.9.0

---

R/data_color.R
R/export.R
R/format_vec.R
R/helpers.R
R/shiny.R
R/utils.R
R/utils_render_latex.R
R/zzz.R
man/as_latex.Rd
man/gt-options.Rd

This fixes a bug where LaTeX tables generated through the `xelatex` LaTeX engine wouldn't work (because of the `amsmath` package). That package has been removed from the default set. It is modifiable now through global options (the `gt.latex_packages` option).
Fixes: https://github.com/rstudio/gt/issues/751

Modify vector of LaTeX packages and place these defaults in global options

---

R/dt_options.R
R/gt_group.R
R/opts.R
R/render_as_i_html.R
R/tab_create_modify.R
man/grp_options.Rd
man/opt_interactive.Rd
man/tab_options.Rd
tests/testthat/helper-gt_attr_expectations.R

This PR adds the `ihtml.use_text_wrapping` option in `tab_options()` and `use_text_wrapping` in `opt_interactive()`. This will provide the option to wrap text lines (or not) in interactive HTML tables.

Add the `ihtml.use_text_wrapping` option for interactive tables

---

tests/testthat/test-gt_group.R

This PR adds tests that encompass the `grp_*()` function family.

Add tests for the `grp_*()` family of functions

---

R/modify_columns.R
tests/testthat/test-cols_label_with.R

The `cols_label_with()` won't properly relabel column labels if the resolved columns is only a subset of the total columns available. This fix ensures that the column name information isn't lost during the process of altering the existing column labels.

Fix error in `cols_label_with()`

---

R/utils_render_latex.R
R/zzz.R

This adds some facility for background fill colors and text coloring/bolding to be rendered in LaTeX tables. Other types of styling (including in other locations such as the column labels) will be handled in a later PR.

Add ability to render background fills and text colors for LaTeX body cells

---

R/export.R
R/utils_render_xml.R

This provides greater compatibility of `gt_group` objects (created via `gt_split()` or `gt_group()`) with `gtsave()`. Previously, we could generate standalone Word and RTF documents from these objects but the work here now allows for HTML and LaTeX document generation. Attempting to create a PDF or PNG from a `gt_group` object results in an error (as before), though now there is a clear explanation and workaround offered.
Fixes: https://github.com/rstudio/gt/issues/1354

Allow wider use of `gtsave()` with `gt_group` objects

---

R/render_as_i_html.R
R/utils_formatters.R

This fixes the problem where certain types of formatting weren't correctly applied to body cells in interactive HTML tables.
Fixes: https://github.com/rstudio/gt/issues/1384
Fixes: https://github.com/rstudio/gt/issues/1370
Fixes: https://github.com/rstudio/gt/issues/1299

Fix lack of HTML formatting for body cells in interactive tables

---

.github/workflows/build-site.yaml
R/format_data.R
R/helpers.R
R/tab_create_modify.R
man/fmt_bytes.Rd
man/fmt_currency.Rd
man/fmt_date.Rd
man/fmt_datetime.Rd
man/fmt_engineering.Rd
man/fmt_flag.Rd
man/fmt_fraction.Rd
man/fmt_image.Rd
man/fmt_index.Rd
man/fmt_integer.Rd
man/fmt_markdown.Rd
man/fmt_number.Rd
man/fmt_partsper.Rd
man/fmt_passthrough.Rd
man/fmt_percent.Rd
man/fmt_roman.Rd
man/fmt_scientific.Rd
man/fmt_spelled_num.Rd
man/fmt_time.Rd
man/fmt_url.Rd
man/from_column.Rd
man/tab_stub_indent.Rd

This adds more documentation around which functions the `from_column()` helper supports and which specific arguments have support (within their respective help docs, via a standardized section).

Improve `from_column()` docs and add sections to relevant functions

---

NEWS.md
R/utils_render_xml.R
tests/testthat/test-as_word.R

Thank you for contributing to **gt**! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
This PR addresses the new summary_rows and grand_summary_rows argument for "side", as well as addressing the situation where a table may have no rownames normally, but has a grand summary row, so it needs to have a blank rowname column listed.
- Ref: #1325

Word respect group summary location

---

R/modify_columns.R
man/cols_nanoplot.Rd

Change "are" to "and" in cols_nanoplot

Fix tiny typo in cols_nanoplot description

---

R/utils_render_latex.R
tests/testthat/_snaps/tab_stub_indent.md

When performing indents in the stub, it's ideal to have them in `pt` units (instead of the `px` value that's stored internally). There are LaTeX flavors that don't automatically handle the conversion of `px` to `pt`. This PR does that conversion automatically for better compatibility.
Fixes: https://github.com/rstudio/gt/issues/1417

Convert length units to pt in indentation when in LaTeX render

---

NEWS.md
R/utils_plots.R

This corrects the calculation of the *y*-axis scale, taking into account all plot elements and expansion of scale. The rendering of the *y*-axis guide is now correct over all cases. Finally, the reference line has been modified so as to project over the entire width of the plot area instead of terminating at the min/max data point *x* values.

Fix calculation and rendering of y-axis scale

---

DESCRIPTION
NEWS.md
R/dt_styles.R
R/utils_render_html.R
R/utils_render_rtf.R
R/z_utils_render_footnotes.R
tests/testthat/test-tab_options.R

Rendering slightly bigger tables (e.g. 50k rows) as HTML is very slow. The two main culprits are `create_body_component_h()` and {htmltools} (in particular `tagWrite()` but also creating the tags themself).
Two small benchmarks
```r
diamonds_1000 <- ggplot2::diamonds |>
head(1000) |>
gt::gt()
diamonds <- ggplot2::diamonds |>
gt::gt()
prepare <- function(data) {
data <- gt:::build_data(data = data, context = "html")
data <- gt:::add_css_styles(data = data)
gt:::create_body_component_h(data = data)
}
bench::mark(
diamonds_1000 = prepare(diamonds_1000),
diamonds = prepare(diamonds),
check = FALSE
)
```
`create_body_component_h()` is quite huge. I think it would make sense to split parts of it into separate functions, e.g. a function for the group headings, the summaries, the data itself. I …

Improve performance of `render_html()`

---

NEWS.md
R/export.R
man/gtsave.Rd

Have gtsave follow more closely `ggsave()` by returning the file path instead of `TRUE`.
This is a naive solution. I guess the code could be cleaned up a little bit for `gtsave()` since the related htmltools issue seems to have been solved. May no longer require this fs code? 
Some tests seem to be a little redundant too? I could take another (more thorough) shot at the `gtsave()` code and tests if you think this is worth pursuing.

Make gtsave return file path invisibly.

---

R/data_color.R
R/dt_heading.R
R/export.R
R/format_data.R
R/gt-package.R
R/helpers.R
R/utils.R
R/utils_examples.R
R/utils_render_xml.R
R/z_utils_render_footnotes.R
tests/testthat/helper-gt_attr_expectations.R
tests/testthat/test-as_word.R
tests/testthat/test-conditional_fmt.R
tests/testthat/test-data_color.R
tests/testthat/test-gt_group.R
tests/testthat/test-image.R
tests/testthat/test-l_cols_align.R
tests/testthat/test-l_cols_merge.R
tests/testthat/test-l_cols_move.R
tests/testthat/test-l_conditional_fmt.R
tests/testthat/test-l_row_group_order.R
tests/testthat/test-l_tab_spanner_delim.R
tests/testthat/test-l_table_parts.R
tests/testthat/test-r_table_parts.R
tests/testthat/test-summary_rows.R
tests/testthat/test-table_parts.R
tests/testthat/test-utils_units.R

Hi Rich, here is some minor refactoring of code in R/ and tests/. I see failures locally, but wanted to check if it is reproducible on CI.
Edit: I can reproduce the test failure with gt 0.10.0, so I filed an issue for that. (i.e. not a bug that I introduced)

Misc Code refactoring.

---

NEWS.md
R/utils.R
tests/testthat/helper-render_formats.R
tests/testthat/test-input_data_validation.R

Use `rlang::caller_env()` to help user find the source of the error more easily.
```r
mtcars |> fmt_number()
Error in `stop_if_not_gt_tbl()`:
! The `data` provided is not a `gt_tbl` object.
mtcars |> fmt_number()
Error in `fmt_number()`:
! `data` must be a `gt_tbl` object, not a data frame.
```

Improve error message for gt functions

---

R/export.R
R/utils_render_latex.R
tests/testthat/test-as_latex.R
tests/testthat/test-cols_width.R

This pull request addresses two previously-reported bugs associated with outputting tables to LaTeX.  
1.   Issue #1465:   Fixes an issue where table columns specified with the `pct` function cause LaTeX compilation errors.   The error is caused by the fact that specifying `cols_width(everything() ~ pct(20))` specifies the column width in LaTeX as "20%".  Since % is the comment symbol in LaTeX, this produces a compilation error.  The code has been changed so that the column width in LaTeX will be output as "0.2\linewidth" if the table width is unspecified (in which case each column will take up 20% of the available width) or 0.2 times the specified table width.
2.  Issue #119 (and duplicate issue #329):   Uses the user-supplied table widths to establish the LaTeX tables widths.  The code …

Issue 1465

---

R/utils_plots.R

This change addresses a situation where all `y` values in a plot are zero. Previously, we'd handled the situation where all `y` values are the same and addressed the scale issue by centering the horizontal value between y limits that were (+/-)20% about the `y` values. For the all-zero case, this calculation results in upper/lower y scale limits that are zero, making the display look poor.
Fixes: https://github.com/rstudio/gt/issues/1486

Handle special nanoplot case where all `y` values are zero

---

R/utils_render_latex.R
tests/testthat/_snaps/tab_footnote.md

When creating tables in LaTeX, if there are multiple footnotes, footnotes without an explicit superscript are preceded by "\\textsuperscript{NA}" when rendered.  This pull request removes these NAs.
The change replaces a series of `paste0` calls with calls to a new function, `sprintf_unless_na`, that returns an NA_character_ when an NA is passed to the function.  (I switched from `paste0` to `sprintf` because it's slightly more streamlined -- using `paste0` would have required three arguments be passed each time.)
The existing tests are sufficient to cover this pull request, though the snapshots for three tests have to be modified to show results without NA's preceding the unnumbered footnotes.  Those modifications are included in the pull request.
I'm assuming this is a 
- Ref: #1416 
- …

Resolve Issue 1416

---

R/modify_columns.R
R/utils_plots.R
man/cols_nanoplot.Rd

This allows for single line bar plots in `cols_nanoplot()`. If the `plot_type` is set to `"bar"` and single values are found, then horizontal bars will be generated. With single bars, the width is meaningless unless compared against other single values found across other rows. If there is a combination of single values and multiple values within the collection of rows, the single-value bar plots will only be proportional to the other single values (i.e., the different plot views won't interfere with each other).
Here is a simple example:
```r
library(gt)
dplyr::tibble(
a = c(4.6, 0.2, 5.6, 6.3, 0, NA)
) %>%
gt() %>%
cols_nanoplot(columns = a, plot_type = "bar")
```
This also adds the `autoscale` arg so that plots can have a shared `y` and even `x` scale.

Allow for nanoplot output of horizontal bars 

---

R/utils_plots.R

The changes here allow for nanoplots that are essentially single-valued bars (when `plot_type = "bar"` and there is just a single value to plot) to display in positive and negative directions. A zero-value line marker is now displayed. Negative values have a different color (obtained from the `data_bar_negative_stroke_color` arg in `nanoplot_options()`) and other settable display attributes.
Here are some examples:
```r
library(gt)
dplyr::tibble(
a = c(4.6, 0.2, 5.6, 6.3, 0, NA)
) |>
gt() |>
cols_nanoplot(columns = a, plot_type = "bar") |>
tab_style(
style = cell_borders(sides = c("left", "right"), weight = "2px"),
locations = cells_body(columns = nanoplots)
)
```
```r
dplyr::tibble(
a = c(-4.6, -0.2, -5.6, -6.3, 0, NA)
) |>
gt() |>
cols_nanoplot(columns = a, plot_type …
```

Positive and negative horizontal-barplot nanoplots

---

R/helpers.R
R/modify_columns.R
R/utils_plots.R
man/nanoplot_options.Rd

This PR makes single-bar nanoplots display their values on hover. As these types of nanoplots can have a mix of positive, negative, and zero-value bars, it was important to ensure that the compactly-formatted data values are affixed to the zero-line, with the text anchored on the appropriate side. Zero value labels were adjusted to lie in a more central position (since there is no bar). The user could hover virtually anywhere in the cell and the value will then appear (i.e., the hover area is large for convenience).
Here we also add the `interactive_data_values` argument to the `nanoplot_options()` function. This allows for having persistent data values shown on the single-bar nanoplots. This may be desirable in some cases since there is only a single value per nanoplot (i.e., clutter …

Add hoverable data values for single-bar nanoplots

---

R/utils.R
R/zzz.R

Small performance improvement - no longer calls `utils::packageVersion` 
Fixes: [#1524](https://github.com/rstudio/gt/issues/1524)

Possible performance improvement - call `utils::packageVersion` only once

---

R/modify_columns.R
man/cols_nanoplot.Rd

This adds the `autohide` argument to the `cols_nanoplot()` function. As in several other `cols_*()` functions, there is the `autohide` argument to automatically hide columns that participate as input but become redundant after the function is invoking. 
In this case, inputs to `cols_nanoplot()` provide data for the nanoplot in a separate column. Once the plot is made, the data in the input column(s) is likely going to require a separate `cols_hide()` call to hide the columns providing the input. We can save the trouble in doing so with the `autohide = TRUE` default (same default for all functions having an `autohide` argument). For those cases where the input column *should* remain visible, the user is able to set `autohide = FALSE`.

Add the `autohide` argument to `cols_nanoplot()`

---

R/helpers.R
R/modify_columns.R
R/utils_plots.R
man/nanoplot_options.Rd

The fill color for the area that bounds the data points in line plot type of nanoplot can now be changed through this PR. The default value is `"#FF0000"` (`"red"`), which is unchanged from before. This can be modified via `nanoplot_options()`'s `data_area_fill_color` argument.
Here is an example of this:
```r
library(gt)
illness |>
dplyr::slice_head(n = 10) |>
gt(rowname_col = "test") |>
tab_header("Partial summary of daily tests performed on YF patient") |>
tab_stubhead(label = md("**Test**")) |>
cols_hide(columns = c(starts_with("norm"), starts_with("day"))) |>
fmt_units(columns = units) |>
cols_nanoplot(
columns = starts_with("day"),
new_col_name = "nanoplots",
new_col_label = md("*Progression*"),
options = nanoplot_options(data_area_fill_color = "lightgreen") 
) |> …
```

Add option to change fill color of nanoplot data area (bounded to data points)

---

R/format_data.R
tests/testthat/test-fmt_url.R
tests/testthat/test-helper_functions.R

This change ensures that any URLs generated via `fmt_url()` don't inadvertently break across lines. This fixes an issue where line breaks could occur in Quarto 1.4, affecting the presentation in an adverse way.
Fixes: https://github.com/rstudio/gt/issues/1509

Modify `fmt_url()` URLs such that line breaks don't occur

---

R/utils_render_latex.R
tests/testthat/_snaps/tab_stub_indent.md

This issue addresses Issue #1590 which was supposedly corrected by PR #1450. However, there was a typo in the code and the "px" units were not converted properly to "pt" values. This very small PR does that and I have confirmed that this resolves the bug in #1590. 
- #1590 
- #1450 
- #1417
Fixes: https://github.com/rstudio/gt/issues/1590

Replace px with pt to fix Bug #1590

---

DESCRIPTION
NEWS.md
R/utils_render_rtf.R
tests/testthat/test-utils_render_rtf.R

Simple fix for gtsave() for .rtf with `cols_label()`.
Extended the fix to `grand_summary_rows()` as well!
Note: The other saving tests don't work well on Windows on my machine, maybe double check if they run as expected for you locally? I also have not tested this widely.
Tested that the fix works for both `summary_rows()` and / or `grand_summary_rows()`.
- Ref: fixes #1233
rtf
html

handle correctly rtf saving with cols_label + summary_rows / grand_summary_rows

---

LICENSE.md

This PR runs `usethis::use_mit_license()` to update `LICENSE.md` with the latest template in usethis.
As a result, this change fixes and improves two things:
- The title is now an h1 element so that the [full license page](https://gt.rstudio.com/LICENSE.html) title won't become "NA" in pkgdown (screenshot below).
- The body text now will not contain any non-ASCII characters (curly quotes) but will still be rendered properly in pkgdown because of the [smart quotes interpretation](https://pandoc.org/MANUAL.html#extension-smart) in pandoc.
This is a purely cosmetic change and does not warrant a news item or unit test.
- N/A

Run `usethis::use_mit_license()` to fix license page title

---

R/export.R
R/utils_render_latex.R
tests/testthat/test-as_latex.R

This pull request makes a minor correction to avoid a Latex error when including multiple tables in a Quarto document.
I've simplified the code to avoid having to define the holdLTright and holdLTleft variables, which were causing errors when being redefined in Quarto.  These variables existed because to change the table width, we need to reset the lengths stored in variables LTright and LTleft.  This would create side effects in Latex since changing these would alter them for every table that followed.  As a result, I used holdLTright and holdLTleft to record the lengths of these variables at the very beginning of the table code and then restored those values at the end.
Among the changes made to master by my last PR, was the use of \begingroup and \endgroup at the start and end of the …

Fix Issue #1580

---

R/render_as_i_html.R

This fixes a bug where single footnotes (i.e., exactly one footnote) won't appear in the footer of an interactive table. Using two or greater distinct footnotes works. This simply modifies a conditional statement so that all numbers of footnotes work properly.
Fixes: https://github.com/rstudio/gt/issues/1615

Ensure display of footnotes works properly for interactive tables

---

R/utils.R

In #1504, I made a small typo. The variable name is `call`, not `error_call`
Currently, yields this error.
! `call` must be a call or environment, not a function.

Fix argument name typo

---

R/resolver.R
tests/testthat/test-fmt_percent.R
tests/testthat/test-gtsave.R

#1600 : all fmt-functions (such as `fmt_percent`) didn't work when helper functions such as `md` or `html` for the stub were used
#1626 : was just a problem on local testing at windows env (gtsave: absolute paths beginning with / or ~)
- Ref: #1600 
- Ref: #1626 
Fixes: #1600
Fixes: #1626

fix for fmt-functions in combination with md/html-stubs

---

NEWS.md
R/data_color.R
R/format_data.R
R/format_vec.R
R/resolver.R
R/tab_create_modify.R
R/utils.R
tests/testthat/_snaps/tab_create_modify.md
tests/testthat/test-resolver.R
tests/testthat/test-tab_create_modify.R

Basically uses `withCallingHandlers()` to give more precise location.
These are probably already tested by I used snapshots to display the user-facing messages. Tried to use tidyverse style guide + cli pluralization when possible.
The reprex in #475 now prints.
It mentions which footnote it was to be able to find it more easily + the offending function where column selection couldn't be resolved.
For mentioning the function, you can see that I added manually the name of the function for better display (there were just a couple of instances.
TIL  this in case it can be helpful!
``` r
f <- function(x) {
g(x)
}
f2 <- function(x) {
g(x, call = call("my_fn"))
}
f3 <- function(x) {
f_user_face <- "my_fn"
g(x, call = call(f_user_face))
}
g <- function(x, call = rlang::caller_env()) { …
```

Improve `tab_footnote()` error message

---

R/render_as_i_html.R

When *not* using pagination in interactive tables as in:
```r
library(gt)
gt(iris) |> 
opt_interactive(use_pagination = FALSE)
```
The output would show disabled controls for pagination. This is undesired and the fix here ensure that if `use_pagination` is `FALSE` we don't get any pages or pagination controls.
Fixes: https://github.com/rstudio/gt/issues/1542

Fix unwanted pagination controls

---

R/render_as_i_html.R

When using an interactive table, the locale value (supplied in the initial `gt()` call) is retrieved in order to display elements/controls in the language of the locale. However, there are a few ways to write a locale and internally `normalize_locale()` is used to standardize a provided locale to a chosen form.
This wasn't done in the codepath for making an interactive table so using `"fr_CH"` instead of `"fr-CH"` would have resulted in english text (the result of a failed lookup). This PR ensures that the locale value is normalized so the following code works as expected:
```r
library(gt)
mtcars |> 
mutate(mpg = mpg*1000) |> 
gt(locale = "de_CH") |> # or "fr_CH"
fmt_number(mpg, decimals = 2) |>
opt_interactive()
```
Fixes: https://github.com/rstudio/gt/issues/1637

Ensure that supplied locale is normalized when creating an interactive table

---

DESCRIPTION
R/export.R
R/utils_render_grid.R
tests/testthat/test-utils_render_grid.R

This PR aims to fix #1652. 
Briefly, in the `as_gtable()` approach, it renders cells with the `<svg>` tags using {rsvg} into raster images. It uses a regex pattern to recognise the tag and switches from a 'render plain text' mode to 'render svg' mode via a new internal function `render_grid_svg()`. Most of this function's body is just trying to parse dimensions from the svg string.
- Ref: #1652

Render SVG cells as images in `as_gtable()` output.

---

R/format_data.R
R/format_vec.R
man/fmt_chem.Rd
man/vec_fmt_bytes.Rd
man/vec_fmt_currency.Rd
man/vec_fmt_date.Rd
man/vec_fmt_datetime.Rd
man/vec_fmt_duration.Rd
man/vec_fmt_engineering.Rd
man/vec_fmt_fraction.Rd
man/vec_fmt_index.Rd
man/vec_fmt_integer.Rd
man/vec_fmt_number.Rd
man/vec_fmt_partsper.Rd
man/vec_fmt_percent.Rd
man/vec_fmt_scientific.Rd
man/vec_fmt_spelled_num.Rd
man/vec_fmt_time.Rd

This PR makes small changes that remove irrelevant text from the `vec_fmt_*()` function docs, and, small changes to the documentation of `fmt_chem()`.

Small documentation fixes for `locale` throughout the `vec_fmt_*()` fns; text fixes in docs of `fmt_chem()`

---

R/utils.R

This fixes an error when performing base64 encoding (when preparing strings for Markdown processing in Quarto, through `fmt_markdown()`).

Use `vapply()` when performing base64 encoding

---

data-raw/03-gtcars.R
data-raw/04-sp500.R
data-raw/08-peeps.R
data-raw/09-films.R
data-raw/15-photolysis.R

Fix #1697 
The next time datasets are built, they will remove the readr::spec() attribute. Other datasets don't have this issue.
This is very minor, but it is just that object comparisons will be a little bit easier if we drop these classes.
I didn't rebuild the data as this is minor and this will naturally occur next time you need to add a dataset.
Strategy found in readr 1.3.0 changelog https://readr.tidyverse.org/news/index.html#tibble-data-frame-subclass-1-3-0
Basically, this aims to solve this.
```r
v1 <- gtcars %>% dplyr::slice_head(n = 1, by = year) %>% dplyr::arrange(year)
v2 <- gtcars %>% dplyr::group_by(year) %>%  dplyr::slice_head(n = 1) %>% dplyr::ungroup()
all.equal(v1, v2)
#> [1] "Attributes: < Length mismatch: comparison on first 2 components >"                   
#> [2] …
```

Remove spec() from dataset generation scripts

---

NEWS.md
R/format_data.R
R/info_tables.R
R/modify_columns.R
R/rows_add.R
R/tab_create_modify.R
R/topics.R
man/cols_add.Rd
man/cols_label.Rd
man/cols_nanoplot.Rd
man/fmt_bins.Rd
man/fmt_icon.Rd
man/info_icons.Rd
man/location-helper.Rd
man/rows_add.Rd
man/tab_spanner_delim.Rd
pkgdown/_pkgdown.yml

Regression from #1694 caught by skimming through package index.
Also renamed the locations topic to include a link to main. Adding `text_case_when()` to the list of functions that use `locations`.
~Somehow you can add links in `@family` tags! but `pkgdown::has_concept()` doesn't really recognize it (but that is okay, we can just revert to using `starts_with("cells_")`, like it was before #1658~  Reverted this bit with `gert::git_reset_hard("HEAD~2")` ! (advice from https://github.com/r-lib/pkgdown/issues/2647#issuecomment-2155442376)

Edits pkgdown + fixup of some docs

---

NEWS.md
R/render_as_i_html.R

fixes #1702
~Do you think it is worth adding a new test?~
```r
gt(iris, rownames_to_stub = T) %>% 
opt_interactive()
```
~Maybe the width is too wide? I don't know how to tweak it.~
This PR
Before

Add support for `rowname_to_stub` + `opt_interactive()`

---

R/render_as_i_html.R
tests/testthat/test-i_html.R

Addresses https://github.com/rstudio/gt/issues/1702#issuecomment-2173258752
After a bit of investigation, I also realized that setting `.rownames` doesn't work. https://github.com/glin/reactable/issues/378
Let me know if you can think of a better way to achieve this. 
This is a bit sketchy, because 
```r
row.names(mtcars) <- mtcars$vs
#> Error 
#> Duplicates in row.names are not allowed.
```
before #1706, it would be silently ignored.

fix usage of `rowname_col` for `opt_interactive()`

---

NEWS.md
R/dt_options.R
R/opts.R
R/render_as_i_html.R
R/tab_create_modify.R
man/opt_interactive.Rd
man/tab_options.Rd
tests/testthat/helper-gt_attr_expectations.R

To mitigate #1544, specifying manually height could be useful.
Before, there was no way to prevent overflowing with  `opt_interactive()`. Let me know if there is a better way to do this. I tried modifying the `height` value to `NULL`, or `"auto"` in the `reactable::reactable()` call in `render_as_ihtml()`, but couldn't find a way to do this well. The only way I found was with manual override. Figure a way to find out the RStudio viewer's size. But after my research, I figured that giving the option to user exactly how to set their widget's height was a good way to go?
I am not too familiar with setting options, and this will likely ignore static options set. I don't know which `tab_options()` are expected to have an effect in both interactive and non-interactive?
Before:
```r
mtcars %>% …
```

Add `ihtml.height` for interactive custom widget height

---

R/export.R
R/utils.R
R/utils_formatters.R
R/utils_render_grid.R

This PR aims to fix #1701. Briefly, it swaps the html context for grid context in `as_gtable()`.
This context will format text with `as.character()` only, to avoid the html escape mechanism that renders poorly in graphics.
Please be forewarned that I only have a partial understanding of how contexts work in {gt}, so somebody who is more familiar should double-check whether this is the correct approach.
Here is a reprex from the linked issue, notice that the symbols on the left are now rendered as actual symbols.
``` r
library(tibble)
devtools::load_all("~/packages/gt")
#> ℹ Loading gt
gt0 <- tibble(symbol = c(">", "%", "£", "&")
, value = c(100, 200, 300, 400)) |> 
gt() |> 
fmt_currency(currency = "GBP") |>
as_gtable() |>
plot()
```
<sup>Created on 2024-06-20 with [reprex …

grid context that formats text as-is

---

R/gt_group.R
R/tab_create_modify.R
R/utils_render_html.R
R/utils_render_xml.R

While working on something else, I noticed that the error message for wrong type for options was not informative.
`check_*()` won't allow `NA` by default, although it is possible to override this!
Using `arg = var_name` allows to include the faulty argument's name. (although it will loose its `.` for `_` due to `tidy_gsub()`, but will still be informative!
```r
exibble |> gt() |> tab_options(footnotes.multiline = "\n")
#> Error in `dplyr::mutate()`:
ℹ In argument: `value = mapply(...)`.
Caused by error:
! rlang::is_scalar_logical(option) is not TRUE
#> Error in `tab_options()`:
#> ! `footnotes_multiline` must be `TRUE` or `FALSE`, not the string "\n".
```

Improve error message for `tab_options()` wrong input

---

R/render_as_i_html.R

This PR decreases the time to render an interactive gt table via a more selective definition of `colDef`s. Only those columns that have one or more formatting directives will have their cells rendered, extracted, and passed on to the interactive table.
Fixes: https://github.com/rstudio/gt/issues/1289

Decrease rendering time for interactive tables

---

NEWS.md
R/info_tables.R
man/info_date_style.Rd
man/info_time_style.Rd

To preview time and date styles
With `locale = "fr"`, I got this

Add `locale` to `info_time_style()` and `info_date_style()`

---

R/tab_create_modify.R
tests/testthat/test-table_parts.R

In the case where `id` values inherit directly from the `label` value *and* the `html()` or `md()` helpers are used, strip any HTML tags from `id` to obtain a simplified string. This solves an issue where complicated tags result in problems when retrieving the label value during render.
Fixes: https://github.com/rstudio/gt/issues/1143

Ensure that `id` values are stripped of HTML tags when using `tab_row_group()`

---

R/render_as_i_html.R

Previously, interactive HTML tables had footnotes and source notes built in the same way as static HTML tables. However, the interactive HTML table is built differently (i.e., primarily uses `<div>`s, and no table elements) so that approach only half worked.
This PR builds the tags for source notes and footnotes correctly and, in doing so, the `*.multiline` and `*.sep` are honored in the rendered table.
Fixes: https://github.com/rstudio/gt/issues/1505

Ensure that source notes and footnotes are built correctly for interactive HTML tables

---

NEWS.md
R/render_as_i_html.R
tests/testthat/test-i_html.R
tests/testthat/test-substitution.R

Follow-up to #1702, #1705. Fixes some rough edges for new feature introduced in #1711 and #1725
Intent is respecting `tab_stubhead()` in `opt_interactive()`, by adding `name` to groupname colDef() or rownames where appropriate.
I noticed that `sub_missing()` (and probably all `sub_*()` is ignored in `opt_interactive()`, but that will require more work another time!
For clarity, I also factored out the translations since the intermediate variables are not useful for the final output.
Before this PR, 
```r
exibble |> gt::gt(rowname_col = "num", groupname_col = "group") |> tab_stubhead("row name to show") |> opt_interactive()
```
With this PR, stubhead label shows and NAs are correctly marked as NA instead of `...6`

Respect `tab_stubhead()` in `opt_interactive()`+ fix rendering for missing row names

---

R/render_as_i_html.R

I should have tested before comitting this https://github.com/rstudio/gt/pull/1758#discussion_r1668777820...
If it is not too late, this version actually solves the problem I was trying to solve.

actually fix NA row names in `opt_interactive()`

---

R/modify_columns.R

I noticed a couple of spots in the `cols_merge()` function (and friends), where a selecting character vector of column names was not wrapped in `all_of()`. This can cause errors depending on a users' {lifecycle} messaging setting, e.g when `options(lifecycle_verbosity = "error")`.
In this PR, I just add `all_of()` around those vectors. 🕺🏼 🍁  
closes #1764
- This doesn't seem newsworthy? 
- I don't think there is a needed test for this.

Adding `all_of()` when selecting from vector of colnames

---

NEWS.md
R/quarto.R
R/utils.R
R/utils_render_grid.R
tests/testthat/helper.R
tests/testthat/test-quarto.R

Basically, the underlying problem was that `charToRaw("")` gives `character(0)`.
I therefore replaced the condition `!is.na(x)` by `nzchar(x, keepNA = FALSE)` (a more elegent `!is.na(x) & x != ""`)
I added a mocking mechanism to allow for testing in Quarto functions. I think it is worth adding to it.
For more on mocking, see https://www.tidyverse.org/blog/2023/10/testthat-3-2-0/#mocking.
I could have set a temp env var with `withr::local_envvar()`, but thought it read more clearly this way.
I tested my test and it indeed fails with current main!
Fixes #1769, amends https://github.com/rstudio/gt/pull/1690

Fix empty `md("")` in Quarto

---

.Rbuildignore
NEWS.md
R/dt_cols_merge.R
R/location_methods.R
R/text_transform.R
tests/testthat/_snaps/text_transform.md
tests/testthat/test-text_transform.R

Thought I was done with error messages, but no!
I started this PR as a wish to improve test coverage.
But turns out more work was required to get the `text_*()` to have consistent error messages (similar to `tab_style()` and `tab_footnote()`.
While working on that, I discovered an error in tidyselect (r-lib/tidyselect#352) It means that some errors will improve naturally when the next tidyselect version will be out.
---
Test coverage 
https://app.codecov.io/gh/rstudio/gt/blob/master/R%2Ftext_transform.R
I also deleted dt_col_merge_init() as it is unused in the codebase.  https://app.codecov.io/gh/rstudio/gt/blob/master/R%2Fdt_cols_merge.R
I created the `text_transform_impl()` as a way to easily get `Error in `text_case_match()`
Coverage data https://app.codecov.io/gh/rstudio/gt/pull/1774

Improve `text_*()` error messages

---

NEWS.md
R/export.R
tests/testthat/test-render_as_gtable.R

This PR aims to fix #1771.
Briefly, it works by accounting for `pct()`-widths in `grid_layout_widths()`.
The reprex from the issue now renders:
``` r
devtools::load_all("~/packages/gt/")
#> ℹ Loading gt
start_date <- "2010-06-07"
end_date <- "2010-06-08"
sp_tab <- 
sp500 |>
dplyr::filter(date >= start_date & date <= end_date) |>
gt() |>
cols_width(date ~ pct(50)) |>
as_gtable(plot = TRUE)
```
<sup>Created on 2024-07-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
- Ref: #1771

Pct column widths

---

.github/workflows/pkgdown.yaml
vignettes/case-study-gtcars.Rmd
vignettes/gt-datasets.Rmd
vignettes/gt.Rmd

This sets the ground to adding a Quarto vignette to the site, since pkgdown supports this since 2.1 (which I am working on!)
But I thought it would be useful to run the pkgdown workflow on PRs.

Setup standard pkgdown workflow + install Quarto

---

pkgdown/_pkgdown.yml

This simply adds the light-switch option (for switching between light and dark mode) for the pkgdown website.

Add light-switch option for pkgdown site

---

NEWS.md
R/utils_render_grid.R
tests/testthat/test-as_gtable.R

Split of.
Basically, just due to the fact that like base subsetting,
```r
vctrs::vec_slice(c(1, 2), -integer(0))
#> numeric(0)
c(1, 2)[-integer(0)]
#> numeric(0)
```
which ends up creating an empty layout in this particular case. I have been bitten by this before ;) 
```r
df <- data.frame(x = 1:3, y = 4:6, row = c("A", "B", "C"))
gt(df, groupname_col = "row", row_group_as_column = T) |> plot()
#> Error in body[vertical] + n : 
#> Non-numeric argument
```
This PR:  
Split from #1801 as I am still trying to understand what is going on. What currently works, and what doesn't. I'd like to narrow down the issues and I thought this was a straightforward bug fix!

Fix grid output with unique groups in `groupname_col` and  `row_group_as_column = TRUE`

---

scripts/visual-tests-latex.R

Seems like the visual tests are off to a great start! https://github.com/rstudio/gt/pull/1804#issuecomment-2236314015. Let's add the Quarto version there as an extra layer of safety / reproducibility.

Update visual-tests-latex.R to show Quarto version

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
R/tab_create_modify.R
README.md
tests/testthat/test-as_word.R

The tidyselect warning was hard to catch, I used: (relates to https://github.com/rstudio/gt/pull/1763
tests/testthat/setup.R as 
```r
options(
warnPartialMatchArgs = TRUE,
warnPartialMatchDollar = TRUE,
warnPartialMatchAttr = TRUE,
lifecycle_verbosity = "error"
)
```
We are all clear now.
Also the pkgdown action now installs Quarto by default, so we can remove the hack!

Update actions and badges + remove partial match + tidyselect warning

---

NEWS.md
R/text_transform.R
tests/testthat/test-text_transform.R

Before the PR, we would get 
```r
exibble %>% gt() %>% tab_spanner("the boring spanner", columns = c(num, date)) %>%
text_case_match(
"the boring spanner" ~ "awesome spanner",
.replace = "all",
.locations = cells_column_spanners()
)
#> Error in `dplyr::case_match()` at gt/R/text_transform.R:414:9:
#> ! Can't combine `..1 (right)` <character> and `.default` <list>.
```
Now, it works as expected!

`text_case_match()` now works with `tab_spanner()` + `.replace = "all"`

---

NEWS.md
R/tab_create_modify.R
tests/testthat/test-tab_spanner_delim.R

Avoid spanner ids collision by initializing the existing spanner ids first and then try to resolve the new spanner id
I get the result I expected with the following code
```r
df <- data.frame(
pop_rural_young_num = c(1000, 2000),
pop_rural_young_pct = c(0.33, 0.66),
pop_rural_old_num = c(1000, 2000),
pop_rural_old_pct = c(0.33, 0.66),
pop_urban_young_num = c(1000, 2000),
pop_urban_young_pct = c(0.33, 0.66),
pop_urban_old_num = c(1000, 2000),
pop_urban_old_pct = c(0.33, 0.66)
)
gt::gt(df) %>%
tab_spanner_delim(
delim = "_",
contains("rural"),
limit = 2
) %>%
tab_spanner_delim(
delim = "_",
contains("urban"),
limit = 2
)
```
Previously, I would get this:
```
Error in `tab_spanner()`:
! The spanner `id` provided ("spanner-young_num") is
not unique.
• The `id` must be unique across existing …
```

Avoid a duplicate id error in `tab_spanner_delim()`.

---

.Rbuildignore
R/data_color.R
R/modify_rows.R
R/text_transform.R
R/utils_general_str_formatting.R
R/utils_render_grid.R
R/utils_render_rtf.R
R/z_utils_render_footnotes.R
tests/testthat/_snaps/utils.md
tests/testthat/helper.R
tests/testthat/test-as_raw_html.R
tests/testthat/test-cols_align.R
tests/testthat/test-cols_merge.R
tests/testthat/test-cols_width.R
tests/testthat/test-gt_group.R
tests/testthat/test-l_cols_align.R
tests/testthat/test-substitution.R
tests/testthat/test-summary_rows.R
tests/testthat/test-tab_footnote.R
tests/testthat/test-tab_options.R
tests/testthat/test-tab_remove.R
tests/testthat/test-tab_spanner_delim.R
tests/testthat/test-tab_stub_indent.R
tests/testthat/test-tab_style.R
tests/testthat/test-table_parts.R
tests/testthat/test-text_transform.R
tests/testthat/test-util_functions.R
tests/testthat/test-utils.R
tests/testthat/test-utils_render_grid.R
tests/testthat/test-utils_units.R

* Reduce test duplication
* Add new helper functions to replace some widely used techniques such as matching in a html, removing the html ids
* Reduce pipe usage in codebase and tests
- Ref: #

Lint tests + reduce pipe usage + use test helper to test common patterns

---

NEWS.md
R/format_vec.R
tests/testthat/test-quarto.R

Fix #1840 
Basically, the idea is that since `vec_fmt_markdown()` calls `fmt_markdown()` (and not the other way around, we can use some code to trick `vec_fmt_markdown()` to think it is not inside Quarto.
I tried using `on.exit(Sys.unsetenv("QUARTO_BIN_PATH")` but it didn't work for some reason. Would love to not use withr here.
I know tidyselect imports it, so gt has an indirect dep on it, but since withr 3.0 has simplified its code, it is possible they remove that dep at some point.

Correctly output `vec_fmt_markdown()` inside Quarto

---

R/dt_boxhead.R
R/dt_groups_rows.R
R/fmt.R
R/format_data.R
R/gt.R
R/info_tables.R
R/summary_rows.R
R/tab_create_modify.R
R/utils_render_html.R
R/utils_render_latex.R
R/utils_render_xml.R
tests/testthat/test-fmt.R
tests/testthat/test-helper_functions.R
tests/testthat/test-l_fmt_date_time.R
tests/testthat/test-resolver.R
tests/testthat/test-utils_render_grid.R

Avoid unnecessary tidy-eval when possible should speed things up a little

Refactoring to reduce dplyr usage and speed up locale resolution

---

NEWS.md
R/helpers.R
tests/testthat/test-fmt_markdown.R

This PR closes #1882 by ensuring factors are converted to text before converting to markdown when `fmt_markdown()` is used with HTML output. It achieves this by adding `text <- as.character(text)` as the first step in the `md()` function. It also adds a test of rendering a factor column with markdown formatting and updates the NEWS file.
``` r
gt(data.frame(x = factor("TEST"))) |> 
fmt_markdown()
```
<div id="vydivsyvfg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" …

Support factors in `fmt_markdown()` with HTML output

---

R/opts.R
man/opt_table_font.Rd
tests/testthat/test-opts.R

This adds the arguments `size` and `color` to the `opt_table_font()` function. Text in an example is also modified since it provides an incorrect description of the code that follows.
Fixes: https://github.com/rstudio/gt/issues/1879

Add two useful arguments to `opt_table_font()`: `size` and `color`

---

R/dt_spanners.R
R/fmt.R
R/format_data.R
R/format_vec.R
R/helpers.R
R/utils_render_common.R

Improve a little performance for `vec_*()` by avoiding converting to a tibble and remove some dplyr calls to `group_vars()`.
This could probably be improved further, but saw these quick fixes so I added that.
I wonder if this could be improved further. I used the first example of `cols_nanoplot()` 
```r
illness |>
dplyr::slice_head(n = 10) |>
gt(rowname_col = "test") |>
tab_header("Partial summary of daily tests performed on YF patient") |>
tab_stubhead(label = md("**Test**")) |>
cols_hide(columns = starts_with("norm")) |>
fmt_units(columns = units) |>
cols_nanoplot(
columns = starts_with("day"),
new_col_name = "nanoplots",
new_col_label = md("*Progression*")
) |>
cols_align(align = "center", columns = nanoplots) |>
cols_merge(columns = c(test, units), pattern = "{1} ({2})") |> …
```

Misc performance improvements for nanoplots / `vec_*()` functions.

---

NEWS.md
R/build_data.R
R/format_vec.R

By removing some unnecessary build stage operations, we are able to speed up significantly the rendering of the `vec_fmt_*()`  functions and hence `cols_nanoplot()`.
This seems to double speed by avoiding unnecessary operations!
- follow up to #1888

Improve performance of vec_fmt_*() by not building the full data

---

R/utils_render_common.R
tests/testthat/_snaps/cols_merge.md
tests/testthat/test-cols_merge.R

Just because before, I got this bizzare error message, took me a while to understand.
```
Erreur dans .transformer(expr, env) : objet '2' introuvable
```

improve cols_merge error message with bad pattern

---

NEWS.md
R/build_data.R
R/cols_add.R
R/cols_align_decimal.R
R/dt_body.R
R/fmt.R
R/nanoplot.R
R/tab_create_modify.R
R/utils.R
R/utils_render_common.R
R/utils_render_rtf.R
R/z_utils_render_footnotes.R
tests/testthat/_snaps/cols_add.md
tests/testthat/test-cols_add.R
tests/testthat/test-cols_nanoplot.R

Hopefully, my last one. 
My example is down to about 4 seconds rendering time.
The main idea is to avoid dplyr or coercion to tibble and also avoid to check for the compatibility of the formatter unnecessarily. 
I realized `cols_add()` has some issues, so I fixed up the two corner cases `.before = 0` and `.after = last_col()` + added tests.
Also eliminated some tidyselect deprecation warnings
- Ref: #1888 , #1891

Performance of vec_fmt_*() by avoiding checking of compatibility + coercion to tibble

---

NEWS.md
R/gt.R
R/zzz.R
man/gt-options.Rd
man/gt.Rd

The idea is to avoid stuff like this
````qmd
---
title: "un document en français"
lang: fr
---
```{r}
options(gt.locale = "fr-CA")
```
```{r}
gt(exibble) |> fmt_number()
```
```{r}
gt(exibble)
```
````
.
Of course, if you provide locale explicitly anywhere in the calls, it would have precedence on the global option. Please let me know what you think. I see it as a useful way to specify `locale` globally in a Quarto document / project. 
I hoped we could be smarter by detecting `lang` in Quarto, but it isn't possible. Let me know if you have an alternative idea! I know you are not a fan of global options 
https://github.com/quarto-dev/quarto-cli/discussions/10886

Add `gt.locale` option

---

R/cols_align.R
R/data_color.R
R/export.R
R/extract.R
R/format_data.R
R/format_vec.R
R/image.R
R/info_tables.R
R/nanoplot.R
R/opts.R
R/summary_rows.R
R/tab_create_modify.R
R/tab_footnote.R
R/text_transform.R
R/utils_color_contrast.R
R/utils_plots.R

Continuing on the work @olivroy has been doing, this PR makes a few more replacements of `arg_match()` to `arg_match0()` to increase performance.
With a particularly demanding set of nanoplots in the table of the following code, we get a pretty decent speedup.
```r
library(gt)
gibraltar |>
dplyr::filter(date <= "2023-05-14") |>
dplyr::mutate(time = as.numeric(hms::as_hms(paste0(time, ":00")))) |>
dplyr::mutate(humidity = humidity * 100) |>
dplyr::select(date, time, temp, humidity, wind_speed) |>
dplyr::group_by(date) |>
dplyr::summarize(
time = paste(time, collapse = ","),
temp = paste(temp, collapse = ","),
humidity = paste(humidity, collapse = ","),
wind_speed = paste(wind_speed, collapse = ","),
) |>
dplyr::mutate(is_satsun = lubridate::wday(date) %in% c(1, 7)) |>
gt(rowname_col = …
```

Arg match replacements (`arg_match()` -> `arg_match0()`)

---

NEWS.md
R/utils_render_common.R

This PR improves the performance of `rownum_translation()`, replacing an inefficient loop with `match()`. Closes #1924.
- Ref: #1924

More efficient `rownum_translation()`

---

NEWS.md
R/export.R
tests/testthat/test-as_gtable.R

This PR aims to fix #1923.
I've tried to mirror to CSS specifications more closely with the constraint that grid can't automatically reflow text.
See examples below.
- Ref: #1923
- Test change: #1776
Based on the reprex in the linked issue, showing the plot with no total width contraints, a relative width and an absolute width contraint.
``` r
devtools::load_all("~/packages/gt/")
#> ℹ Loading gt
library(gtExtras)
start_date <- "2010-06-07"
end_date <- "2010-06-08"
sp_tab <- 
sp500 %>%
select(-c(volume, adj_close)) %>%
dplyr::filter(date >= start_date & date <= end_date) %>%
gt() %>%
cols_width(date ~ pct(50)) %>%
tab_options(table.font.size = px(12))
plot(sp_tab)
```
``` r
plot(sp_tab %>% tab_options(table.width = pct(80)))
```
``` r
plot(sp_tab %>% …
```

Improve `as_gtable()` width calculations

---

NEWS.md
R/knitr-utils.R
tests/testthat/test-utils_render_html.R

@nielsbock I verified that the captions still work with pdf documents.
In #1800, there was 
```diff
-   lab1 <- "(#"
+   lab1 <- "(\\#"
```
I suspect this was required to make it work with LaTeX?
Therefore, I just branched it and make gt emit a different string whether latex or not.
Verified that the example in the linked issue renders in both bookdown::html_document2 and bookdown::pdf_document2.
(edit: pkgdown CI failure unrelated) 
- Ref: Fixes #1948

fix bookdown::html_document2 cross-ref

---

NEWS.md
R/quarto.R
tests/testthat/_snaps/quarto.md
tests/testthat/test-quarto.R

Basically this reverts [part](https://github.com/rstudio/gt/pull/1860#discussion_r1966003385) of #1860.
As suggested in https://github.com/quarto-dev/quarto-cli/issues/11932#issuecomment-2609871584, we encode to base64 the unprocessed text.
It seems to do the trick and does not seem to introduce regressions (in particular the example in #1773 renders correctly)
For the review, it would be best to investigate this 60f19adec234093eac4fe39780bb363fec2aec85 instead of the full diff because I added tests in the first commit.
@cderv , do you think this is the right approach? 
Fixes #1957 
Fixes https://github.com/quarto-dev/quarto-cli/issues/11932
Fixes https://github.com/quarto-dev/quarto-cli/issues/11610
Here is an issue I found after this change in typst:
* Not getting anything with …

Fix issue with markdown and Quarto

---

NEWS.md
R/fmt.R
tests/testthat/test-fmt_number.R

Surgical (probably incorrect?) fix
fixes #1961

Add workaround for removing the trailing dec mark when sep_mark = ""

---

R/tab_options.R
man/tab_options.Rd

I noticed there is a tiny typo in the helpfile for `tab_options(latex.tbl.pos)` - you can see this in your pkgdown site at <https://gt.rstudio.com/reference/tab_options.html#arg-latex-tbl-pos>, i.e.,
which is now fixed to

Delete extra backtick in tab_options(latex.tbl.pos) helpfile text

---

DESCRIPTION
R/export.R
R/zzz.R

This PR aims to fix #1972. It uses `gt::as_gtable()` to write an S3 method for the `gtable::as.gtable()` generic.
It resolves the registering a method for a suggested package via `vctrs::s3_register()`.
I'm not sure it merits any tests or news bullets, but I'd be happy to add them if needed.
- Ref: #1972

Add `as.gtable()` S3 method
